SELECT * FROM TRAN_VIEW;
SELECT * FROM CARD_BENEFIT_VIEW;
SELECT * FROM CARD_DETAIL_BENEFIT;
SELECT * FROM CARD_IMG_BENE_INFORMATION;
SELECT * FROM CARD_CONSUMPTION_HISTORY;

SELECT * FROM BENE_INFO;
SELECT * FROM INDU_TYPE;

SELECT SMALL_CATE,MIDDLE_CATE,LARGE_CATE,AMOUNT_OF_BUSI,SUBSTR(DATE_OF_USE,0,10) AS DATE_OF_USE FROM CARD_CONSUMPTION_HISTORY
WHERE CARD_NUM = '7817-6800-7171-6558' AND TO_DATE(DATE_OF_USE,'YYYY-MM-DD HH24:MI:SS') BETWEEN TRUNC(SYSDATE,'d')-7 AND TRUNC(SYSDATE,'d')-1 ;

SELECT * FROM CARD_CONSUMPTION_HISTORY WHERE MEMBER_NUM = '2222' ORDER BY DATE_OF_USE DESC;

SELECT * FROM CUSTOMER_CARD_INFO;
SELECT * FROM CARD_INFO;
SELECT * FROM CARD_BENEFIT_VIEW;

SELECT * FROM CUSTOMER_CARD_INFO;



SELECT * FROM CARD_DETAIL_BENEFIT;

SELECT * 
FROM CUSTOMER_CARD_INFO A,CARD_DETAIL_BENEFIT B
WHERE A.CARD_CATE_NUM = B.CARD_CATE_NUM;


--DROP VIEW TRAN_VIEW;
--SELECT * FROM TRAN_VIEW;

CREATE OR REPLACE VIEW TRAN_VIEW 
AS 
SELECT A.TRAN_CATE_NUM,B.LARGE_CATE,B.MIDDLE_CATE,B.SMALL_CATE,C.ALI_TYPE 
FROM TRAN_CATE A, INDU_TYPE B, ALI_INFO C
WHERE  A.INDUSTRY_CODE = B.INDU_CODE AND A.ALI_CODE = C.ALI_CODE 
ORDER BY TRAN_CATE_NUM;

--DROP VIEW CARD_BENEFIT_VIEW;
CREATE OR REPLACE VIEW CARD_BENEFIT_VIEW 
AS
SELECT A.ALI_CODE,B.BENE_CODE,A.ALI_TYPE,C.SMALL_CATE FROM
ALI_INFO A,BENE_INFO B,INDU_TYPE C 
WHERE B.ALI_CODE =A.ALI_CODE AND B.INDUSTRY_CODE = C.INDU_CODE ORDER BY A.ALI_CODE;

--특정 카드의 카드 정보 
SELECT * FROM INDU_TYPE;

SELECT * FROM ALI_INFO;

--DROP VIEW CARD_DETAIL_BENEFIT;
SELECT * FROM CARD_BENE;
SELECT * FROM CARD_DETAIL_BENEFIT;

CREATE OR REPLACE VIEW CARD_DETAIL_BENEFIT
AS
SELECT A.CARD_CATE_NUM,B.ALI_TYPE,B.SMALL_CATE,A.BENE_RATE,A.BENE_LIMIT,A.BENE_CODE
FROM CARD_BENE A,CARD_BENEFIT_VIEW B
WHERE A.BENE_CODE = B.BENE_CODE
ORDER BY CARD_CATE_NUM;

SELECT * FROM CARD_BENE;
--이미지와 카드 카테고리와 혜택 정보 

CREATE OR REPLACE VIEW CARD_IMG_BENE_INFORMATION
AS 
SELECT A.IMG_URL, B.CARD_NAME,C.BENE_RATE*100 AS DISCOUNT,B.ANNUAL_FEE_CODE, C.ALI_TYPE,C.SMALL_CATE,B.ANNUAL_FEE,C.BENE_LIMIT,A.CARD_CATE_NUM,B.SORT_CARD,B.CARD_SEG_NUM
FROM CARD_IMG A,CARD_INFO B,CARD_DETAIL_BENEFIT C
WHERE A.CARD_CATE_NUM = B.CARD_CATE_NUM AND  B.CARD_CATE_NUM = C.CARD_CATE_NUM;
SELECT * FROM CARD_DETAIL_BENEFIT;

SELECT CARD_NAME,ANNUAL_FEE_CODE,CARD_CATE_NUM,CARD_SEG_NUM,SORT_CARD
FROM CARD_INFO A,NETWORK_IMG B
WHERE
A.ANNUAL_FEE_CODE = B.ANNUAL_FEE_CODE
AND CARD_CATE_NUM = 'CR00001'; 


SELECT A.CARD_NAME,IMG_URL,A.ANNUAL_FEE_CODE
FROM
CARD_INFO A,NETWORK_IMG B
WHERE CARD_CATE_NUM =(SELECT CARD_CATE_NUM
FROM CARD_INFO WHERE CARD_SEG_NUM = 'SE00001')
AND A.ANNUAL_FEE_CODE = B.ANNUAL_FEE_CODE;

--특정 인원의 카드 소비 내역 WHERE 절로 제어함 
CREATE OR REPLACE VIEW CARD_CONSUMPTION_HISTORY
AS 
SELECT B.MEMBER_NUM,A.NAME,A.EMAIL_ADDRESS,A.GENDER,A.IDENTITY,B.CARD_NUM,B.TRAN_CATE_NUM,B.DATE_OF_USE,B.AMOUNT_OF_BUSI,C.LARGE_CATE,C.MIDDLE_CATE,C.SMALL_CATE,C.ALI_TYPE 
FROM 
CUSTOMER_INFO A,
TRAN_INFO B,
TRAN_VIEW C
WHERE A.MEMBER_NUM = B.MEMBER_NUM AND B.TRAN_CATE_NUM=C.TRAN_CATE_NUM; 
