DROP INDEX INDU_TYPE_INDEX;
CREATE INDEX INDU_TYPE_INDEX ON INDU_TYPE(SMALL_CATE);
SELECT * FROM INDU_TYPE;
--CREATE INDEX INDU_CODE_INDEX ON INDU_TYPE(INDU_CODE,SMALL_CATE);

DROP INDEX TRAN_CATE_INDEX;
CREATE INDEX TRAN_CATE_INDEX ON TRAN_CATE(TRAN_CATE_NUM);
SELECT * FROM TRAN_CATE;

DROP INDEX INDU_TYPE_INDEX;
CREATE INDEX INDU_TYPE_INDEX ON INDU_TYPE(SMALL_CATE);
SELECT * FROM INDU_TYPE;


DROP INDEX CUSTOMER_INDEX;
CREATE INDEX CUSTOMER_INDEX ON CUSTOMER_INFO(MEMBER_NUM);
SELECT * FROM CUSTOMER_INFO;

DROP INDEX CLUSTER_INDEX;
CREATE INDEX CLUSTER_INDEX ON CLUSTERED_CUSTOMER(CLUSTERED,MEMBER_NUM);
SELECT * FROM CLUSTERED_CUSTOMER;

SELECT B.SMALL_CATE,ROUND(SUM(B.AMOUNT_OF_BUSI)/3) AS AMOUNT_OF_BUSI,COUNT(B.SMALL_CATE) AS COUNT FROM  
(SELECT * 
FROM CLUSTERED_CUSTOMER  
WHERE CLUSTERED =1) A, CARD_CONSUMPTION_HISTORY B
WHERE A.MEMBER_NUM = B.MEMBER_NUM 
AND TO_DATE(DATE_OF_USE,'YYYY-MM-DD HH24:MI:SS') BETWEEN ADD_MONTHS(TRUNC(SYSDATE,'MM'),-3) AND LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE,'MM'),-1)) 
GROUP BY B.SMALL_CATE 
ORDER BY AMOUNT_OF_BUSI DESC;	

DROP INDEX TRAN_INFO_INDEX;
SELECT * FROM TRAN_INFO;
CREATE INDEX TRAN_INFO_INDEX ON TRAN_INFO(MEMBER_NUM,TRAN_CATE_NUM);

SELECT B.MEMBER_NUM,A.NAME,A.EMAIL_ADDRESS,A.GENDER,A.IDENTITY,B.CARD_NUM,B.TRAN_CATE_NUM,B.DATE_OF_USE,B.AMOUNT_OF_BUSI,C.SMALL_CATE,C.ALI_TYPE 
FROM 
CUSTOMER_INFO A,
TRAN_INFO B,
TRAN_VIEW C
WHERE A.MEMBER_NUM = B.MEMBER_NUM AND B.TRAN_CATE_NUM=C.TRAN_CATE_NUM 
ORDER BY B.MEMBER_NUM;



--이거 쓰니까 성능 개선됨 
--3초 -> 0.1초 로 단축 

SELECT * FROM USER_OBJECTS WHERE OBJECT_TYPE ='INDEX';

SELECT B.MEMBER_NUM,A.EMAIL_ADDRESS,B.TRAN_CATE_NUM,SUM(B.AMOUNT_OF_BUSI),C.ALI_TYPE,C.MIDDLE_CATE
FROM 
CUSTOMER_INFO A,
TRAN_INFO B,
TRAN_VIEW C
WHERE A.MEMBER_NUM = B.MEMBER_NUM AND B.TRAN_CATE_NUM = C.TRAN_CATE_NUM 
GROUP BY B.MEMBER_NUM, A.EMAIL_ADDRESS ,B.TRAN_CATE_NUM,C.ALI_TYPE,C.MIDDLE_CATE
ORDER BY B.MEMBER_NUM;

SELECT * FROM CARD_CONSUMPTION_HISTORY WHERE MEMBER_NUM = '5000' ORDER BY DATE_OF_USE DESC;